spring.application.name=exchange-rate-api
exchange-rate.api.base-url=https://api.exchangerate.host
exchange-rate.api.access-key=${EXCHANGE_RATE_API_KEY}
spring.cache.type=caffeine
spring.cache.cache-names=latestRates
spring.cache.caffeine.spec=expireAfterWrite=1m,maximumSize=10