spring.application.name=exchange-rate-api
exchange-rate.api.base-url=https://api.exchangerate.host
exchange-rate.api.access-key=${EXCHANGE_RATE_API_ACCESS_KEY}
spring.cache.type=caffeine
spring.cache.cache-names=latestRates
spring.cache.caffeine.spec=expireAfterWrite=1m,maximumSize=1
app.security.username=${APP_SECURITY_USERNAME}
app.security.password=${APP_SECURITY_PASSWORD}
exchange-rate.api.connect-timeout=2s
exchange-rate.api.read-timeout=5s