spring.application.name=exchange-rate-api

exchange-rate.api.base-url=https://api.exchangerate.host
exchange-rate.api.access-key=${EXCHANGE_RATE_API_ACCESS_KEY}
exchange-rate.api.connect-timeout=2s
exchange-rate.api.read-timeout=5s

spring.cache.type=caffeine
spring.cache.cache-names=latestRates
spring.cache.caffeine.spec=expireAfterWrite=1m,maximumSize=1

spring.security.oauth2.resourceserver.jwt.issuer-uri=${JWT_ISSUER_URI}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWT_JWK_SET_URI}

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

spring.graphql.graphiql.enabled=true